import fs from 'node:fs/promises';
import {decryptJson,encryptJson} from './crypto.mjs';
import {buildAnalytics,buildPortfolioAnalytics} from './analytics.mjs';

const FILE=new URL('../docs/data/portfolio.enc.json',import.meta.url);const task=process.env.TASK||'daily';
const required=name=>{const v=(process.env[name]||'').trim();if(!v)throw new Error(`Falta ${name}`);return v};
const key=required('DASHBOARD_KEY');const payload=JSON.parse(await fs.readFile(FILE,'utf8'));const data=decryptJson(payload,key);
const iso=d=>d.toISOString().slice(0,10);const today=iso(new Date());
async function eod(ticker,token){const from=iso(new Date(Date.now()-370*864e5));const url=new URL(`https://eodhd.com/api/eod/${encodeURIComponent(ticker)}`);url.search=new URLSearchParams({api_token:token,fmt:'json',period:'d',order:'d',from,to:today});const r=await fetch(url,{headers:{'User-Agent':'MiCartera/2.0'}});if(!r.ok)throw new Error(`EODHD ${r.status}`);const rows=(await r.json()).filter(x=>x?.date&&Number(x.close)>0).sort((a,b)=>String(a.date).localeCompare(String(b.date)));if(!rows.length)throw new Error('sin cotización');const x=rows.at(-1);return{nav:Number(x.close),date:x.date,rows:rows.map(row=>({date:row.date,nav:Number(row.close)}))}}
const unescapeXml=value=>value.replace(/<!\[CDATA\[|\]\]>/g,'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');
async function refreshMarket(errors){
  const feeds=[
    {source:'BCE',url:'https://www.ecb.europa.eu/rss/press.html'},
    {source:'Reserva Federal',url:'https://www.federalreserve.gov/feeds/press_all.xml'}
  ];
  const headlines=[];
  for(const feed of feeds){
    try{
      const response=await fetch(feed.url,{headers:{'User-Agent':'MiCartera/2.0'}});
      if(!response.ok)throw new Error(`HTTP ${response.status}`);
      const xml=await response.text();
      for(const item of xml.match(/<item\b[\s\S]*?<\/item>/gi)||[]){
        const get=tag=>unescapeXml((item.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)<\\/${tag}>`,'i'))||[])[1]||'').trim();
        const title=get('title'),url=get('link'),rawDate=get('pubDate')||get('dc:date');
        if(title&&url)headlines.push({source:feed.source,title,url,date:rawDate?iso(new Date(rawDate)):today});
      }
    }catch(error){errors.push({source:feed.source,error:`noticias: ${error.message}`})}
  }
  headlines.sort((a,b)=>String(b.date).localeCompare(String(a.date)));
  data.market??={};
  if(headlines.length)data.market.headlines=headlines.slice(0,8);
  data.market.generated_at=new Date().toISOString();
  data.market.errors=errors.filter(x=>x.source);
}
function recompute(){const total=data.positions.reduce((a,p)=>a+p.market_value,0);for(const p of data.positions){p.weight_pct=total?100*p.market_value/total:0;p.financial_gain=p.market_value-p.financial_cost;p.financial_return_pct=p.financial_cost?100*p.financial_gain/p.financial_cost:null;p.tax_gain=p.market_value-p.tax_cost;p.tax_return_pct=p.tax_cost?100*p.tax_gain/p.tax_cost:null}const cost=data.positions.reduce((a,p)=>a+p.financial_cost,0),taxCost=data.positions.reduce((a,p)=>a+p.tax_cost,0);const prev=data.history.at(-1);data.summary={value:total,financial_cost:cost,financial_gain:total-cost,financial_return_pct:cost?100*(total-cost)/cost:null,tax_cost:taxCost,tax_gain:total-taxCost,tax_return_pct:taxCost?100*(total-taxCost)/taxCost:null,position_count:data.positions.length,as_of:data.positions.map(p=>p.nav_date).sort().at(-1),weekly_change:prev?total-prev.value:null,weekly_change_pct:prev&&prev.value?100*(total-prev.value)/prev.value:null,top_positions:[...data.positions].sort((a,b)=>b.market_value-a.market_value).slice(0,5).map(p=>({name:p.name,isin:p.isin,market_value:p.market_value,weight_pct:p.weight_pct,financial_return_pct:p.financial_return_pct}))};const by={};for(const p of data.positions)by[p.strategy]=(by[p.strategy]||0)+p.market_value;data.allocations.strategy=Object.entries(by).map(([label,value])=>({label,weight:100*value/total})).sort((a,b)=>b.weight-a.weight);data.analytics=data.positions.map(position=>buildAnalytics(position,data.nav_history?.[position.isin]||[]));data.portfolio_analytics=buildPortfolioAnalytics(data.positions)}
async function refresh(){const token=required('EODHD_API_TOKEN');const errors=[];let fx=1;try{fx=(await eod('EURUSD.FOREX',token)).nav}catch(e){errors.push({isin:'EURUSD',error:e.message})}for(const p of data.positions){if(p.isin.startsWith('MODEL-'))continue;try{const q=await eod(`${p.isin}.EUFUND`,token);if(q.nav<=0||q.date<p.nav_date)throw new Error('dato no más reciente');if(p.nav>0&&Math.abs(q.nav/p.nav-1)>.25)throw new Error('variación superior al 25%; requiere revisión');p.nav=q.nav;p.nav_date=q.date;p.market_value=p.units*q.nav/(p.currency==='USD'?fx:1);p.nav_source='EODHD · cierre verificado';data.nav_history[p.isin]??=[];const merged=new Map(data.nav_history[p.isin].map(row=>[row.date,row]));for(const row of q.rows)merged.set(row.date,row);data.nav_history[p.isin]=[...merged.values()].sort((a,b)=>a.date.localeCompare(b.date)).slice(-370)}catch(e){errors.push({isin:p.isin,error:e.message})}}for(const c of data.managed_components||[]){try{const q=await eod(`${c.isin}.EUFUND`,token);const navEur=q.nav/(c.currency==='USD'?fx:1);if(c.nav_eur&&Math.abs(navEur/c.nav_eur-1)>.25)throw new Error('variación superior al 25%');c.previous_nav_eur=c.nav_eur||navEur;c.nav_eur=navEur;c.nav_date=q.date}catch(e){errors.push({isin:c.isin,error:e.message})}}const metal=data.positions.find(p=>p.isin==='MODEL-METAL');const comps=(data.managed_components||[]).filter(c=>c.nav_eur&&c.previous_nav_eur);if(metal&&comps.length){const coverage=comps.reduce((a,c)=>a+c.weight,0);const r=comps.reduce((a,c)=>a+(c.weight/coverage)*(c.nav_eur/c.previous_nav_eur-1),0);metal.market_value*=1+r;metal.nav=metal.market_value;metal.nav_date=comps.map(c=>c.nav_date).sort().at(-1);metal.nav_source=`Estimación automática · ${coverage.toFixed(2)}% cubierto`;data.allocations.lookthrough_coverage_pct=metal.market_value/data.positions.reduce((a,p)=>a+p.market_value,0)*100;data.nav_history[metal.isin]??=[];if(!data.nav_history[metal.isin].some(row=>row.date===metal.nav_date))data.nav_history[metal.isin].push({date:metal.nav_date,nav:metal.nav})}await refreshMarket(errors);recompute();if(!data.history.some(x=>x.date===today))data.history.push({date:today,value:data.summary.value});else data.history.find(x=>x.date===today).value=data.summary.value;data.updated_at=new Date().toISOString();data.update_errors=errors;return errors}
function emailHtml(){const s=data.summary;const rows=data.positions.sort((a,b)=>b.market_value-a.market_value).map(p=>`<tr><td style="padding:8px;border-bottom:1px solid #ddd">${p.name}</td><td style="padding:8px;border-bottom:1px solid #ddd;text-align:right">${p.market_value.toLocaleString('es-ES',{style:'currency',currency:'EUR'})}</td><td style="padding:8px;border-bottom:1px solid #ddd;text-align:right">${p.financial_return_pct.toFixed(2)}%</td></tr>`).join('');const news=(data.market?.headlines||[]).map(x=>`<li><a href="${x.url}">${x.title}</a> — ${x.source}</li>`).join('')||'<li>Sin titulares oficiales verificados.</li>';return`<div style="font-family:Arial;color:#15312d;max-width:720px;margin:auto"><h1>Informe semanal de Mi Cartera</h1><p>Datos verificados hasta ${s.as_of}. Si una fuente no respondió, se mantuvo el último valor confirmado.</p><div style="background:#0f6b5d;color:white;padding:20px;border-radius:12px"><div>Valor de mercado</div><strong style="font-size:32px">${s.value.toLocaleString('es-ES',{style:'currency',currency:'EUR'})}</strong><p>Rentabilidad financiera: ${s.financial_return_pct.toFixed(2)}%</p></div><h2>Posiciones</h2><table style="border-collapse:collapse;width:100%">${rows}</table><h2>Mercados</h2><ul>${news}</ul><p><strong>Escenarios, no predicciones ciertas:</strong> ${(data.market?.scenarios||[]).map(x=>`${x.label}: ${x.text}`).join(' · ')}</p><p style="font-size:12px;color:#667">Información educativa; no constituye asesoramiento financiero.</p></div>`}
async function sendWeekly(){const api=required('BREVO_API_KEY'),to=required('REPORT_RECIPIENT'),sender=required('REPORT_SENDER_EMAIL');const r=await fetch('https://api.brevo.com/v3/smtp/email',{method:'POST',headers:{'api-key':api,'content-type':'application/json','accept':'application/json'},body:JSON.stringify({sender:{name:'Mi Cartera',email:sender},to:[{email:to}],subject:`Mi Cartera · informe semanal ${today}`,htmlContent:emailHtml()})});if(!r.ok)throw new Error(`Brevo ${r.status}: ${(await r.text()).slice(0,300)}`)}
if(task==='daily'||task==='both')await refresh();if(task==='weekly'||task==='both')await sendWeekly();await fs.writeFile(FILE,JSON.stringify(encryptJson(data,key))+'\n');console.log(JSON.stringify({ok:true,task,updated_at:data.updated_at,errors:data.update_errors?.length||0}));
